In [2]:
## PRACTISE

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [4]:
data = pd.read_csv("C:/Users/gaurm/Desktop/MACHINE LEARNING/TITANIC/train.csv")
data["Survived"].value_counts()/data.shape[0]

0    0.616162
1    0.383838
Name: Survived, dtype: float64

In [5]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [8]:
data['Age'].fillna(29.0,inplace = True)

In [9]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
data.dropna(axis = 1,how = "any",inplace = True)

In [11]:
data["Sex"]=data["Sex"].map({"female": 1, "male": 0})

In [12]:
#DATA SPLIT

In [13]:
x_train,x_test,y_train,y_test = train_test_split(data[['Age','Sex','Parch','Pclass']],\
                                                      data['Survived'],test_size=0.33,random_state=1)

In [14]:
#FIT THE MODEL
logr = LogisticRegression()
logr.fit( x_train, y_train)

LogisticRegression()

In [15]:
logr.intercept_###Bo value

array([2.20205524])

In [16]:
logr.coef_

array([[-0.03669377,  2.65670786, -0.07510332, -1.17486497]])

In [17]:
##equation: 1/1+e**-(-0.03669377)*Age+2.65670786*Sex+(-0.07510332*Parch)+(-1.17486497*Pclass)

In [18]:
#TEST

In [19]:
predicted_test = logr.predict(x_test)
print(predicted_test)

[1 0 1 1 1 0 0 1 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 1 1 0 1 1 0 0 1 0 1 0
 0 1 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 1 0 0 0 0 0
 1 0 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1 1 0 1 1 0 1 0 0
 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 1 1 1 0 1 0 0 0 1 0 1 1 0 0 1
 0 0 1 0 1 0 0 1 1 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0
 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 0 1 0
 1 1 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0]


In [20]:
#Once we have built model on training data its work is over,TRAINING DATA only used in building the model
##EVALUATION
#Confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,predicted_test).ravel()
print("tn, fp, fn, tp ")

tn, fp, fn, tp 


In [21]:
confusion_matrix(y_test,predicted_test).ravel()

array([148,  26,  37,  84], dtype=int64)

In [22]:

pd.crosstab(y_test,predicted_test)

col_0       0   1
Survived         
0         148  26
1          37  84

In [23]:
Accuracy = (148+84)/y_test.shape[0]
Error = (37+26)/y_test.shape[0]
Recall = (84)/(84+37)
Precision = (84)/(84+26)

In [24]:
newData = print("Accuracy is:{}\nError is:{}\nRecall is :{} \nPrecision is:{}".format(Accuracy,Error,Recall,Precision))

Accuracy is:0.7864406779661017
Error is:0.2135593220338983
Recall is :0.6942148760330579 
Precision is:0.7636363636363637


In [25]:
train = pd.concat([x_train,y_train],axis = 1)
train.head()

Age  Sex  Parch  Pclass  Survived
496  54.0    1      0       1         1
14   14.0    1      0       3         0
82   29.0    1      0       3         1
657  32.0    1      1       3         0
388  29.0    0      0       3         0

In [26]:
import statsmodels.formula.api as sm
LR = sm.logit('Survived ~ Age+Sex+Parch+Pclass',data = train)
result=LR.fit()
result.summary()

Optimization terminated successfully.
         Current function value: 0.428008
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               Survived   No. Observations:                  596
Model:                          Logit   Df Residuals:                      591
Method:                           MLE   Df Model:                            4
Date:                Fri, 11 Nov 2022   Pseudo R-squ.:                  0.3509
Time:                        20:28:22   Log-Likelihood:                -255.09
converged:                       True   LL-Null:                       -392.99
Covariance Type:            nonrobust   LLR p-value:                 1.794e-58
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.3021      0.524      4.395      0.000       1.276       3.329
Age           -0.0381      0.009     -4.077      0.000      -0.056      -0.020
Sex            2.8207      0.243     11.613      0.000       2.345       3.297
Parch         -0.0986      0.141     -0.700      0.484      -0.375       0.177
Pclass        -1.2271      0.152     -8.087      0.000      -1.524      -0.930
==============================================================================
"""

In [50]:
l = data['PassengerId']

In [54]:
m= predicted_test

In [64]:
submission_df = pd.DataFrame()
submission_df['PassengerId'] = x_test.index
submission_df['Survived'] = predicted_test
submission_df.head()

PassengerId  Survived
0          862         1
1          223         0
2           84         1
3          680         1
4          535         1

In [58]:
submission_df.to_csv("TITANIC RESULT")